// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hero.proto

#ifndef PROTOBUF_hero_2eproto__INCLUDED
#define PROTOBUF_hero_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace TableProto {
class hero;
class heroDefaultTypeInternal;
extern heroDefaultTypeInternal _hero_default_instance_;
}  // namespace TableProto

namespace TableProto {

namespace protobuf_hero_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_hero_2eproto

// ===================================================================

class hero : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:TableProto.hero) */ {
 public:
  hero();
  virtual ~hero();

  hero(const hero& from);

  inline hero& operator=(const hero& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  hero(hero&& from) noexcept
    : hero() {
    *this = ::std::move(from);
  }

  inline hero& operator=(hero&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const hero& default_instance();

  static inline const hero* internal_default_instance() {
    return reinterpret_cast<const hero*>(
               &_hero_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(hero* other);
  friend void swap(hero& a, hero& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline hero* New() const PROTOBUF_FINAL { return New(NULL); }

  hero* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const hero& from);
  void MergeFrom(const hero& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(hero* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int64 recomme_skill = 26;
  int recomme_skill_size() const;
  void clear_recomme_skill();
  static const int kRecommeSkillFieldNumber = 26;
  ::google::protobuf::int64 recomme_skill(int index) const;
  void set_recomme_skill(int index, ::google::protobuf::int64 value);
  void add_recomme_skill(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      recomme_skill() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_recomme_skill();

  // string Name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // string Initials = 3;
  void clear_initials();
  static const int kInitialsFieldNumber = 3;
  const ::std::string& initials() const;
  void set_initials(const ::std::string& value);
  #if LANG_CXX11
  void set_initials(::std::string&& value);
  #endif
  void set_initials(const char* value);
  void set_initials(const char* value, size_t size);
  ::std::string* mutable_initials();
  ::std::string* release_initials();
  void set_allocated_initials(::std::string* initials);

  // string Tab = 22;
  void clear_tab();
  static const int kTabFieldNumber = 22;
  const ::std::string& tab() const;
  void set_tab(const ::std::string& value);
  #if LANG_CXX11
  void set_tab(::std::string&& value);
  #endif
  void set_tab(const char* value);
  void set_tab(const char* value, size_t size);
  ::std::string* mutable_tab();
  ::std::string* release_tab();
  void set_allocated_tab(::std::string* tab);

  // string Des = 23;
  void clear_des();
  static const int kDesFieldNumber = 23;
  const ::std::string& des() const;
  void set_des(const ::std::string& value);
  #if LANG_CXX11
  void set_des(::std::string&& value);
  #endif
  void set_des(const char* value);
  void set_des(const char* value, size_t size);
  ::std::string* mutable_des();
  ::std::string* release_des();
  void set_allocated_des(::std::string* des);

  // int64 ID = 1;
  void clear_id();
  static const int kIDFieldNumber = 1;
  ::google::protobuf::int64 id() const;
  void set_id(::google::protobuf::int64 value);

  // int64 Type = 4;
  void clear_type();
  static const int kTypeFieldNumber = 4;
  ::google::protobuf::int64 type() const;
  void set_type(::google::protobuf::int64 value);

  // int64 Level = 5;
  void clear_level();
  static const int kLevelFieldNumber = 5;
  ::google::protobuf::int64 level() const;
  void set_level(::google::protobuf::int64 value);

  // int64 BaseSkill = 6;
  void clear_baseskill();
  static const int kBaseSkillFieldNumber = 6;
  ::google::protobuf::int64 baseskill() const;
  void set_baseskill(::google::protobuf::int64 value);

  // int64 Battle = 7;
  void clear_battle();
  static const int kBattleFieldNumber = 7;
  ::google::protobuf::int64 battle() const;
  void set_battle(::google::protobuf::int64 value);

  // int64 Develop = 8;
  void clear_develop();
  static const int kDevelopFieldNumber = 8;
  ::google::protobuf::int64 develop() const;
  void set_develop(::google::protobuf::int64 value);

  // int64 Auxiliary = 9;
  void clear_auxiliary();
  static const int kAuxiliaryFieldNumber = 9;
  ::google::protobuf::int64 auxiliary() const;
  void set_auxiliary(::google::protobuf::int64 value);

  // int64 BattleBase = 10;
  void clear_battlebase();
  static const int kBattleBaseFieldNumber = 10;
  ::google::protobuf::int64 battlebase() const;
  void set_battlebase(::google::protobuf::int64 value);

  // int64 DevelopBase = 11;
  void clear_developbase();
  static const int kDevelopBaseFieldNumber = 11;
  ::google::protobuf::int64 developbase() const;
  void set_developbase(::google::protobuf::int64 value);

  // int64 AuxiliaryBase = 12;
  void clear_auxiliarybase();
  static const int kAuxiliaryBaseFieldNumber = 12;
  ::google::protobuf::int64 auxiliarybase() const;
  void set_auxiliarybase(::google::protobuf::int64 value);

  // int64 BattleStep = 13;
  void clear_battlestep();
  static const int kBattleStepFieldNumber = 13;
  ::google::protobuf::int64 battlestep() const;
  void set_battlestep(::google::protobuf::int64 value);

  // int64 DevelopStep = 14;
  void clear_developstep();
  static const int kDevelopStepFieldNumber = 14;
  ::google::protobuf::int64 developstep() const;
  void set_developstep(::google::protobuf::int64 value);

  // int64 AuxiliaryStep = 15;
  void clear_auxiliarystep();
  static const int kAuxiliaryStepFieldNumber = 15;
  ::google::protobuf::int64 auxiliarystep() const;
  void set_auxiliarystep(::google::protobuf::int64 value);

  // int64 BattleExtra = 16;
  void clear_battleextra();
  static const int kBattleExtraFieldNumber = 16;
  ::google::protobuf::int64 battleextra() const;
  void set_battleextra(::google::protobuf::int64 value);

  // int64 DevelopExtra = 17;
  void clear_developextra();
  static const int kDevelopExtraFieldNumber = 17;
  ::google::protobuf::int64 developextra() const;
  void set_developextra(::google::protobuf::int64 value);

  // int64 AuxiliaryExtra = 18;
  void clear_auxiliaryextra();
  static const int kAuxiliaryExtraFieldNumber = 18;
  ::google::protobuf::int64 auxiliaryextra() const;
  void set_auxiliaryextra(::google::protobuf::int64 value);

  // int64 ItemID = 19;
  void clear_itemid();
  static const int kItemIDFieldNumber = 19;
  ::google::protobuf::int64 itemid() const;
  void set_itemid(::google::protobuf::int64 value);

  // int64 ItemCount = 20;
  void clear_itemcount();
  static const int kItemCountFieldNumber = 20;
  ::google::protobuf::int64 itemcount() const;
  void set_itemcount(::google::protobuf::int64 value);

  // int64 ExchangeItemID = 21;
  void clear_exchangeitemid();
  static const int kExchangeItemIDFieldNumber = 21;
  ::google::protobuf::int64 exchangeitemid() const;
  void set_exchangeitemid(::google::protobuf::int64 value);

  // int64 Pic = 24;
  void clear_pic();
  static const int kPicFieldNumber = 24;
  ::google::protobuf::int64 pic() const;
  void set_pic(::google::protobuf::int64 value);

  // int64 Show_hero = 25;
  void clear_show_hero();
  static const int kShowHeroFieldNumber = 25;
  ::google::protobuf::int64 show_hero() const;
  void set_show_hero(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:TableProto.hero)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > recomme_skill_;
  mutable int _recomme_skill_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr initials_;
  ::google::protobuf::internal::ArenaStringPtr tab_;
  ::google::protobuf::internal::ArenaStringPtr des_;
  ::google::protobuf::int64 id_;
  ::google::protobuf::int64 type_;
  ::google::protobuf::int64 level_;
  ::google::protobuf::int64 baseskill_;
  ::google::protobuf::int64 battle_;
  ::google::protobuf::int64 develop_;
  ::google::protobuf::int64 auxiliary_;
  ::google::protobuf::int64 battlebase_;
  ::google::protobuf::int64 developbase_;
  ::google::protobuf::int64 auxiliarybase_;
  ::google::protobuf::int64 battlestep_;
  ::google::protobuf::int64 developstep_;
  ::google::protobuf::int64 auxiliarystep_;
  ::google::protobuf::int64 battleextra_;
  ::google::protobuf::int64 developextra_;
  ::google::protobuf::int64 auxiliaryextra_;
  ::google::protobuf::int64 itemid_;
  ::google::protobuf::int64 itemcount_;
  ::google::protobuf::int64 exchangeitemid_;
  ::google::protobuf::int64 pic_;
  ::google::protobuf::int64 show_hero_;
  mutable int _cached_size_;
  friend struct protobuf_hero_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// hero

// int64 ID = 1;
inline void hero::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 hero::id() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.ID)
  return id_;
}
inline void hero::set_id(::google::protobuf::int64 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.ID)
}

// string Name = 2;
inline void hero::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& hero::name() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.Name)
  return name_.GetNoArena();
}
inline void hero::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:TableProto.hero.Name)
}
#if LANG_CXX11
inline void hero::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:TableProto.hero.Name)
}
#endif
inline void hero::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:TableProto.hero.Name)
}
inline void hero::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:TableProto.hero.Name)
}
inline ::std::string* hero::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:TableProto.hero.Name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* hero::release_name() {
  // @@protoc_insertion_point(field_release:TableProto.hero.Name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void hero::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:TableProto.hero.Name)
}

// string Initials = 3;
inline void hero::clear_initials() {
  initials_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& hero::initials() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.Initials)
  return initials_.GetNoArena();
}
inline void hero::set_initials(const ::std::string& value) {
  
  initials_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:TableProto.hero.Initials)
}
#if LANG_CXX11
inline void hero::set_initials(::std::string&& value) {
  
  initials_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:TableProto.hero.Initials)
}
#endif
inline void hero::set_initials(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  initials_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:TableProto.hero.Initials)
}
inline void hero::set_initials(const char* value, size_t size) {
  
  initials_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:TableProto.hero.Initials)
}
inline ::std::string* hero::mutable_initials() {
  
  // @@protoc_insertion_point(field_mutable:TableProto.hero.Initials)
  return initials_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* hero::release_initials() {
  // @@protoc_insertion_point(field_release:TableProto.hero.Initials)
  
  return initials_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void hero::set_allocated_initials(::std::string* initials) {
  if (initials != NULL) {
    
  } else {
    
  }
  initials_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), initials);
  // @@protoc_insertion_point(field_set_allocated:TableProto.hero.Initials)
}

// int64 Type = 4;
inline void hero::clear_type() {
  type_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 hero::type() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.Type)
  return type_;
}
inline void hero::set_type(::google::protobuf::int64 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.Type)
}

// int64 Level = 5;
inline void hero::clear_level() {
  level_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 hero::level() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.Level)
  return level_;
}
inline void hero::set_level(::google::protobuf::int64 value) {
  
  level_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.Level)
}

// int64 BaseSkill = 6;
inline void hero::clear_baseskill() {
  baseskill_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 hero::baseskill() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.BaseSkill)
  return baseskill_;
}
inline void hero::set_baseskill(::google::protobuf::int64 value) {
  
  baseskill_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.BaseSkill)
}

// int64 Battle = 7;
inline void hero::clear_battle() {
  battle_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 hero::battle() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.Battle)
  return battle_;
}
inline void hero::set_battle(::google::protobuf::int64 value) {
  
  battle_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.Battle)
}

// int64 Develop = 8;
inline void hero::clear_develop() {
  develop_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 hero::develop() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.Develop)
  return develop_;
}
inline void hero::set_develop(::google::protobuf::int64 value) {
  
  develop_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.Develop)
}

// int64 Auxiliary = 9;
inline void hero::clear_auxiliary() {
  auxiliary_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 hero::auxiliary() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.Auxiliary)
  return auxiliary_;
}
inline void hero::set_auxiliary(::google::protobuf::int64 value) {
  
  auxiliary_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.Auxiliary)
}

// int64 BattleBase = 10;
inline void hero::clear_battlebase() {
  battlebase_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 hero::battlebase() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.BattleBase)
  return battlebase_;
}
inline void hero::set_battlebase(::google::protobuf::int64 value) {
  
  battlebase_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.BattleBase)
}

// int64 DevelopBase = 11;
inline void hero::clear_developbase() {
  developbase_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 hero::developbase() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.DevelopBase)
  return developbase_;
}
inline void hero::set_developbase(::google::protobuf::int64 value) {
  
  developbase_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.DevelopBase)
}

// int64 AuxiliaryBase = 12;
inline void hero::clear_auxiliarybase() {
  auxiliarybase_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 hero::auxiliarybase() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.AuxiliaryBase)
  return auxiliarybase_;
}
inline void hero::set_auxiliarybase(::google::protobuf::int64 value) {
  
  auxiliarybase_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.AuxiliaryBase)
}

// int64 BattleStep = 13;
inline void hero::clear_battlestep() {
  battlestep_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 hero::battlestep() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.BattleStep)
  return battlestep_;
}
inline void hero::set_battlestep(::google::protobuf::int64 value) {
  
  battlestep_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.BattleStep)
}

// int64 DevelopStep = 14;
inline void hero::clear_developstep() {
  developstep_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 hero::developstep() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.DevelopStep)
  return developstep_;
}
inline void hero::set_developstep(::google::protobuf::int64 value) {
  
  developstep_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.DevelopStep)
}

// int64 AuxiliaryStep = 15;
inline void hero::clear_auxiliarystep() {
  auxiliarystep_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 hero::auxiliarystep() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.AuxiliaryStep)
  return auxiliarystep_;
}
inline void hero::set_auxiliarystep(::google::protobuf::int64 value) {
  
  auxiliarystep_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.AuxiliaryStep)
}

// int64 BattleExtra = 16;
inline void hero::clear_battleextra() {
  battleextra_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 hero::battleextra() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.BattleExtra)
  return battleextra_;
}
inline void hero::set_battleextra(::google::protobuf::int64 value) {
  
  battleextra_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.BattleExtra)
}

// int64 DevelopExtra = 17;
inline void hero::clear_developextra() {
  developextra_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 hero::developextra() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.DevelopExtra)
  return developextra_;
}
inline void hero::set_developextra(::google::protobuf::int64 value) {
  
  developextra_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.DevelopExtra)
}

// int64 AuxiliaryExtra = 18;
inline void hero::clear_auxiliaryextra() {
  auxiliaryextra_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 hero::auxiliaryextra() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.AuxiliaryExtra)
  return auxiliaryextra_;
}
inline void hero::set_auxiliaryextra(::google::protobuf::int64 value) {
  
  auxiliaryextra_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.AuxiliaryExtra)
}

// int64 ItemID = 19;
inline void hero::clear_itemid() {
  itemid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 hero::itemid() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.ItemID)
  return itemid_;
}
inline void hero::set_itemid(::google::protobuf::int64 value) {
  
  itemid_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.ItemID)
}

// int64 ItemCount = 20;
inline void hero::clear_itemcount() {
  itemcount_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 hero::itemcount() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.ItemCount)
  return itemcount_;
}
inline void hero::set_itemcount(::google::protobuf::int64 value) {
  
  itemcount_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.ItemCount)
}

// int64 ExchangeItemID = 21;
inline void hero::clear_exchangeitemid() {
  exchangeitemid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 hero::exchangeitemid() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.ExchangeItemID)
  return exchangeitemid_;
}
inline void hero::set_exchangeitemid(::google::protobuf::int64 value) {
  
  exchangeitemid_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.ExchangeItemID)
}

// string Tab = 22;
inline void hero::clear_tab() {
  tab_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& hero::tab() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.Tab)
  return tab_.GetNoArena();
}
inline void hero::set_tab(const ::std::string& value) {
  
  tab_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:TableProto.hero.Tab)
}
#if LANG_CXX11
inline void hero::set_tab(::std::string&& value) {
  
  tab_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:TableProto.hero.Tab)
}
#endif
inline void hero::set_tab(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  tab_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:TableProto.hero.Tab)
}
inline void hero::set_tab(const char* value, size_t size) {
  
  tab_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:TableProto.hero.Tab)
}
inline ::std::string* hero::mutable_tab() {
  
  // @@protoc_insertion_point(field_mutable:TableProto.hero.Tab)
  return tab_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* hero::release_tab() {
  // @@protoc_insertion_point(field_release:TableProto.hero.Tab)
  
  return tab_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void hero::set_allocated_tab(::std::string* tab) {
  if (tab != NULL) {
    
  } else {
    
  }
  tab_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), tab);
  // @@protoc_insertion_point(field_set_allocated:TableProto.hero.Tab)
}

// string Des = 23;
inline void hero::clear_des() {
  des_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& hero::des() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.Des)
  return des_.GetNoArena();
}
inline void hero::set_des(const ::std::string& value) {
  
  des_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:TableProto.hero.Des)
}
#if LANG_CXX11
inline void hero::set_des(::std::string&& value) {
  
  des_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:TableProto.hero.Des)
}
#endif
inline void hero::set_des(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  des_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:TableProto.hero.Des)
}
inline void hero::set_des(const char* value, size_t size) {
  
  des_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:TableProto.hero.Des)
}
inline ::std::string* hero::mutable_des() {
  
  // @@protoc_insertion_point(field_mutable:TableProto.hero.Des)
  return des_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* hero::release_des() {
  // @@protoc_insertion_point(field_release:TableProto.hero.Des)
  
  return des_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void hero::set_allocated_des(::std::string* des) {
  if (des != NULL) {
    
  } else {
    
  }
  des_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), des);
  // @@protoc_insertion_point(field_set_allocated:TableProto.hero.Des)
}

// int64 Pic = 24;
inline void hero::clear_pic() {
  pic_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 hero::pic() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.Pic)
  return pic_;
}
inline void hero::set_pic(::google::protobuf::int64 value) {
  
  pic_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.Pic)
}

// int64 Show_hero = 25;
inline void hero::clear_show_hero() {
  show_hero_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 hero::show_hero() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.Show_hero)
  return show_hero_;
}
inline void hero::set_show_hero(::google::protobuf::int64 value) {
  
  show_hero_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.Show_hero)
}

// repeated int64 recomme_skill = 26;
inline int hero::recomme_skill_size() const {
  return recomme_skill_.size();
}
inline void hero::clear_recomme_skill() {
  recomme_skill_.Clear();
}
inline ::google::protobuf::int64 hero::recomme_skill(int index) const {
  // @@protoc_insertion_point(field_get:TableProto.hero.recomme_skill)
  return recomme_skill_.Get(index);
}
inline void hero::set_recomme_skill(int index, ::google::protobuf::int64 value) {
  recomme_skill_.Set(index, value);
  // @@protoc_insertion_point(field_set:TableProto.hero.recomme_skill)
}
inline void hero::add_recomme_skill(::google::protobuf::int64 value) {
  recomme_skill_.Add(value);
  // @@protoc_insertion_point(field_add:TableProto.hero.recomme_skill)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
hero::recomme_skill() const {
  // @@protoc_insertion_point(field_list:TableProto.hero.recomme_skill)
  return recomme_skill_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
hero::mutable_recomme_skill() {
  // @@protoc_insertion_point(field_mutable_list:TableProto.hero.recomme_skill)
  return &recomme_skill_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace TableProto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_hero_2eproto__INCLUDED
