// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hero.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "hero.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace TableProto {
class heroDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<hero>
     _instance;
} _hero_default_instance_;

namespace protobuf_hero_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hero, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hero, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hero, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hero, initials_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hero, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hero, level_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hero, baseskill_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hero, battle_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hero, develop_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hero, auxiliary_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hero, battlebase_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hero, developbase_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hero, auxiliarybase_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hero, battlestep_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hero, developstep_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hero, auxiliarystep_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hero, battleextra_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hero, developextra_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hero, auxiliaryextra_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hero, itemid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hero, itemcount_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hero, exchangeitemid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hero, tab_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hero, des_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hero, pic_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hero, show_hero_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hero, recomme_skill_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(hero)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_hero_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "hero.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _hero_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_hero_default_instance_);}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\nhero.proto\022\nTableProto\"\345\003\n\004hero\022\n\n\002ID\030"
      "\001 \001(\003\022\014\n\004Name\030\002 \001(\t\022\020\n\010Initials\030\003 \001(\t\022\014\n"
      "\004Type\030\004 \001(\003\022\r\n\005Level\030\005 \001(\003\022\021\n\tBaseSkill\030"
      "\006 \001(\003\022\016\n\006Battle\030\007 \001(\003\022\017\n\007Develop\030\010 \001(\003\022\021"
      "\n\tAuxiliary\030\t \001(\003\022\022\n\nBattleBase\030\n \001(\003\022\023\n"
      "\013DevelopBase\030\013 \001(\003\022\025\n\rAuxiliaryBase\030\014 \001("
      "\003\022\022\n\nBattleStep\030\r \001(\003\022\023\n\013DevelopStep\030\016 \001"
      "(\003\022\025\n\rAuxiliaryStep\030\017 \001(\003\022\023\n\013BattleExtra"
      "\030\020 \001(\003\022\024\n\014DevelopExtra\030\021 \001(\003\022\026\n\016Auxiliar"
      "yExtra\030\022 \001(\003\022\016\n\006ItemID\030\023 \001(\003\022\021\n\tItemCoun"
      "t\030\024 \001(\003\022\026\n\016ExchangeItemID\030\025 \001(\003\022\013\n\003Tab\030\026"
      " \001(\t\022\013\n\003Des\030\027 \001(\t\022\013\n\003Pic\030\030 \001(\003\022\021\n\tShow_h"
      "ero\030\031 \001(\003\022\025\n\rrecomme_skill\030\032 \003(\003b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 520);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "hero.proto", &protobuf_RegisterTypes);
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_hero_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int hero::kIDFieldNumber;
const int hero::kNameFieldNumber;
const int hero::kInitialsFieldNumber;
const int hero::kTypeFieldNumber;
const int hero::kLevelFieldNumber;
const int hero::kBaseSkillFieldNumber;
const int hero::kBattleFieldNumber;
const int hero::kDevelopFieldNumber;
const int hero::kAuxiliaryFieldNumber;
const int hero::kBattleBaseFieldNumber;
const int hero::kDevelopBaseFieldNumber;
const int hero::kAuxiliaryBaseFieldNumber;
const int hero::kBattleStepFieldNumber;
const int hero::kDevelopStepFieldNumber;
const int hero::kAuxiliaryStepFieldNumber;
const int hero::kBattleExtraFieldNumber;
const int hero::kDevelopExtraFieldNumber;
const int hero::kAuxiliaryExtraFieldNumber;
const int hero::kItemIDFieldNumber;
const int hero::kItemCountFieldNumber;
const int hero::kExchangeItemIDFieldNumber;
const int hero::kTabFieldNumber;
const int hero::kDesFieldNumber;
const int hero::kPicFieldNumber;
const int hero::kShowHeroFieldNumber;
const int hero::kRecommeSkillFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

hero::hero()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_hero_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:TableProto.hero)
}
hero::hero(const hero& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      recomme_skill_(from.recomme_skill_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  initials_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.initials().size() > 0) {
    initials_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.initials_);
  }
  tab_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.tab().size() > 0) {
    tab_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.tab_);
  }
  des_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.des().size() > 0) {
    des_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.des_);
  }
  ::memcpy(&id_, &from.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&show_hero_) -
    reinterpret_cast<char*>(&id_)) + sizeof(show_hero_));
  // @@protoc_insertion_point(copy_constructor:TableProto.hero)
}

void hero::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  initials_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  tab_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  des_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&show_hero_) -
      reinterpret_cast<char*>(&id_)) + sizeof(show_hero_));
  _cached_size_ = 0;
}

hero::~hero() {
  // @@protoc_insertion_point(destructor:TableProto.hero)
  SharedDtor();
}

void hero::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  initials_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  tab_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  des_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void hero::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* hero::descriptor() {
  protobuf_hero_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_hero_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const hero& hero::default_instance() {
  protobuf_hero_2eproto::InitDefaults();
  return *internal_default_instance();
}

hero* hero::New(::google::protobuf::Arena* arena) const {
  hero* n = new hero;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void hero::Clear() {
// @@protoc_insertion_point(message_clear_start:TableProto.hero)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  recomme_skill_.Clear();
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  initials_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  tab_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  des_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&show_hero_) -
      reinterpret_cast<char*>(&id_)) + sizeof(show_hero_));
  _internal_metadata_.Clear();
}

bool hero::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:TableProto.hero)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(16383u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 ID = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string Name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "TableProto.hero.Name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string Initials = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_initials()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->initials().data(), static_cast<int>(this->initials().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "TableProto.hero.Initials"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 Type = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &type_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 Level = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &level_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 BaseSkill = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &baseskill_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 Battle = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &battle_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 Develop = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &develop_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 Auxiliary = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(72u /* 72 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &auxiliary_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 BattleBase = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(80u /* 80 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &battlebase_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 DevelopBase = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(88u /* 88 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &developbase_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 AuxiliaryBase = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(96u /* 96 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &auxiliarybase_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 BattleStep = 13;
      case 13: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(104u /* 104 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &battlestep_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 DevelopStep = 14;
      case 14: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(112u /* 112 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &developstep_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 AuxiliaryStep = 15;
      case 15: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(120u /* 120 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &auxiliarystep_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 BattleExtra = 16;
      case 16: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(128u /* 128 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &battleextra_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 DevelopExtra = 17;
      case 17: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(136u /* 136 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &developextra_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 AuxiliaryExtra = 18;
      case 18: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(144u /* 144 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &auxiliaryextra_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 ItemID = 19;
      case 19: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(152u /* 152 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &itemid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 ItemCount = 20;
      case 20: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(160u /* 160 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &itemcount_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 ExchangeItemID = 21;
      case 21: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(168u /* 168 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &exchangeitemid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string Tab = 22;
      case 22: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(178u /* 178 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_tab()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->tab().data(), static_cast<int>(this->tab().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "TableProto.hero.Tab"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string Des = 23;
      case 23: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(186u /* 186 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_des()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->des().data(), static_cast<int>(this->des().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "TableProto.hero.Des"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 Pic = 24;
      case 24: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(192u /* 192 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &pic_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 Show_hero = 25;
      case 25: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(200u /* 200 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &show_hero_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int64 recomme_skill = 26;
      case 26: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(210u /* 210 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, this->mutable_recomme_skill())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(208u /* 208 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 2, 210u, input, this->mutable_recomme_skill())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:TableProto.hero)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:TableProto.hero)
  return false;
#undef DO_
}

void hero::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:TableProto.hero)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 ID = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->id(), output);
  }

  // string Name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "TableProto.hero.Name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->name(), output);
  }

  // string Initials = 3;
  if (this->initials().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->initials().data(), static_cast<int>(this->initials().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "TableProto.hero.Initials");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->initials(), output);
  }

  // int64 Type = 4;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(4, this->type(), output);
  }

  // int64 Level = 5;
  if (this->level() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(5, this->level(), output);
  }

  // int64 BaseSkill = 6;
  if (this->baseskill() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(6, this->baseskill(), output);
  }

  // int64 Battle = 7;
  if (this->battle() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(7, this->battle(), output);
  }

  // int64 Develop = 8;
  if (this->develop() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(8, this->develop(), output);
  }

  // int64 Auxiliary = 9;
  if (this->auxiliary() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(9, this->auxiliary(), output);
  }

  // int64 BattleBase = 10;
  if (this->battlebase() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(10, this->battlebase(), output);
  }

  // int64 DevelopBase = 11;
  if (this->developbase() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(11, this->developbase(), output);
  }

  // int64 AuxiliaryBase = 12;
  if (this->auxiliarybase() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(12, this->auxiliarybase(), output);
  }

  // int64 BattleStep = 13;
  if (this->battlestep() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(13, this->battlestep(), output);
  }

  // int64 DevelopStep = 14;
  if (this->developstep() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(14, this->developstep(), output);
  }

  // int64 AuxiliaryStep = 15;
  if (this->auxiliarystep() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(15, this->auxiliarystep(), output);
  }

  // int64 BattleExtra = 16;
  if (this->battleextra() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(16, this->battleextra(), output);
  }

  // int64 DevelopExtra = 17;
  if (this->developextra() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(17, this->developextra(), output);
  }

  // int64 AuxiliaryExtra = 18;
  if (this->auxiliaryextra() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(18, this->auxiliaryextra(), output);
  }

  // int64 ItemID = 19;
  if (this->itemid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(19, this->itemid(), output);
  }

  // int64 ItemCount = 20;
  if (this->itemcount() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(20, this->itemcount(), output);
  }

  // int64 ExchangeItemID = 21;
  if (this->exchangeitemid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(21, this->exchangeitemid(), output);
  }

  // string Tab = 22;
  if (this->tab().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->tab().data(), static_cast<int>(this->tab().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "TableProto.hero.Tab");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      22, this->tab(), output);
  }

  // string Des = 23;
  if (this->des().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->des().data(), static_cast<int>(this->des().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "TableProto.hero.Des");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      23, this->des(), output);
  }

  // int64 Pic = 24;
  if (this->pic() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(24, this->pic(), output);
  }

  // int64 Show_hero = 25;
  if (this->show_hero() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(25, this->show_hero(), output);
  }

  // repeated int64 recomme_skill = 26;
  if (this->recomme_skill_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(26, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _recomme_skill_cached_byte_size_));
  }
  for (int i = 0, n = this->recomme_skill_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64NoTag(
      this->recomme_skill(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:TableProto.hero)
}

::google::protobuf::uint8* hero::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:TableProto.hero)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 ID = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->id(), target);
  }

  // string Name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "TableProto.hero.Name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->name(), target);
  }

  // string Initials = 3;
  if (this->initials().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->initials().data(), static_cast<int>(this->initials().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "TableProto.hero.Initials");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->initials(), target);
  }

  // int64 Type = 4;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(4, this->type(), target);
  }

  // int64 Level = 5;
  if (this->level() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(5, this->level(), target);
  }

  // int64 BaseSkill = 6;
  if (this->baseskill() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(6, this->baseskill(), target);
  }

  // int64 Battle = 7;
  if (this->battle() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(7, this->battle(), target);
  }

  // int64 Develop = 8;
  if (this->develop() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(8, this->develop(), target);
  }

  // int64 Auxiliary = 9;
  if (this->auxiliary() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(9, this->auxiliary(), target);
  }

  // int64 BattleBase = 10;
  if (this->battlebase() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(10, this->battlebase(), target);
  }

  // int64 DevelopBase = 11;
  if (this->developbase() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(11, this->developbase(), target);
  }

  // int64 AuxiliaryBase = 12;
  if (this->auxiliarybase() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(12, this->auxiliarybase(), target);
  }

  // int64 BattleStep = 13;
  if (this->battlestep() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(13, this->battlestep(), target);
  }

  // int64 DevelopStep = 14;
  if (this->developstep() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(14, this->developstep(), target);
  }

  // int64 AuxiliaryStep = 15;
  if (this->auxiliarystep() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(15, this->auxiliarystep(), target);
  }

  // int64 BattleExtra = 16;
  if (this->battleextra() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(16, this->battleextra(), target);
  }

  // int64 DevelopExtra = 17;
  if (this->developextra() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(17, this->developextra(), target);
  }

  // int64 AuxiliaryExtra = 18;
  if (this->auxiliaryextra() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(18, this->auxiliaryextra(), target);
  }

  // int64 ItemID = 19;
  if (this->itemid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(19, this->itemid(), target);
  }

  // int64 ItemCount = 20;
  if (this->itemcount() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(20, this->itemcount(), target);
  }

  // int64 ExchangeItemID = 21;
  if (this->exchangeitemid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(21, this->exchangeitemid(), target);
  }

  // string Tab = 22;
  if (this->tab().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->tab().data(), static_cast<int>(this->tab().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "TableProto.hero.Tab");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        22, this->tab(), target);
  }

  // string Des = 23;
  if (this->des().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->des().data(), static_cast<int>(this->des().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "TableProto.hero.Des");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        23, this->des(), target);
  }

  // int64 Pic = 24;
  if (this->pic() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(24, this->pic(), target);
  }

  // int64 Show_hero = 25;
  if (this->show_hero() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(25, this->show_hero(), target);
  }

  // repeated int64 recomme_skill = 26;
  if (this->recomme_skill_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      26,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::uint32>(
            _recomme_skill_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt64NoTagToArray(this->recomme_skill_, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TableProto.hero)
  return target;
}

size_t hero::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TableProto.hero)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated int64 recomme_skill = 26;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int64Size(this->recomme_skill_);
    if (data_size > 0) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _recomme_skill_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // string Name = 2;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // string Initials = 3;
  if (this->initials().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->initials());
  }

  // string Tab = 22;
  if (this->tab().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->tab());
  }

  // string Des = 23;
  if (this->des().size() > 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->des());
  }

  // int64 ID = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->id());
  }

  // int64 Type = 4;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->type());
  }

  // int64 Level = 5;
  if (this->level() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->level());
  }

  // int64 BaseSkill = 6;
  if (this->baseskill() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->baseskill());
  }

  // int64 Battle = 7;
  if (this->battle() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->battle());
  }

  // int64 Develop = 8;
  if (this->develop() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->develop());
  }

  // int64 Auxiliary = 9;
  if (this->auxiliary() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->auxiliary());
  }

  // int64 BattleBase = 10;
  if (this->battlebase() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->battlebase());
  }

  // int64 DevelopBase = 11;
  if (this->developbase() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->developbase());
  }

  // int64 AuxiliaryBase = 12;
  if (this->auxiliarybase() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->auxiliarybase());
  }

  // int64 BattleStep = 13;
  if (this->battlestep() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->battlestep());
  }

  // int64 DevelopStep = 14;
  if (this->developstep() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->developstep());
  }

  // int64 AuxiliaryStep = 15;
  if (this->auxiliarystep() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->auxiliarystep());
  }

  // int64 BattleExtra = 16;
  if (this->battleextra() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->battleextra());
  }

  // int64 DevelopExtra = 17;
  if (this->developextra() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->developextra());
  }

  // int64 AuxiliaryExtra = 18;
  if (this->auxiliaryextra() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->auxiliaryextra());
  }

  // int64 ItemID = 19;
  if (this->itemid() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->itemid());
  }

  // int64 ItemCount = 20;
  if (this->itemcount() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->itemcount());
  }

  // int64 ExchangeItemID = 21;
  if (this->exchangeitemid() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->exchangeitemid());
  }

  // int64 Pic = 24;
  if (this->pic() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->pic());
  }

  // int64 Show_hero = 25;
  if (this->show_hero() != 0) {
    total_size += 2 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->show_hero());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void hero::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:TableProto.hero)
  GOOGLE_DCHECK_NE(&from, this);
  const hero* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const hero>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:TableProto.hero)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:TableProto.hero)
    MergeFrom(*source);
  }
}

void hero::MergeFrom(const hero& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:TableProto.hero)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  recomme_skill_.MergeFrom(from.recomme_skill_);
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.initials().size() > 0) {

    initials_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.initials_);
  }
  if (from.tab().size() > 0) {

    tab_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.tab_);
  }
  if (from.des().size() > 0) {

    des_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.des_);
  }
  if (from.id() != 0) {
    set_id(from.id());
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
  if (from.level() != 0) {
    set_level(from.level());
  }
  if (from.baseskill() != 0) {
    set_baseskill(from.baseskill());
  }
  if (from.battle() != 0) {
    set_battle(from.battle());
  }
  if (from.develop() != 0) {
    set_develop(from.develop());
  }
  if (from.auxiliary() != 0) {
    set_auxiliary(from.auxiliary());
  }
  if (from.battlebase() != 0) {
    set_battlebase(from.battlebase());
  }
  if (from.developbase() != 0) {
    set_developbase(from.developbase());
  }
  if (from.auxiliarybase() != 0) {
    set_auxiliarybase(from.auxiliarybase());
  }
  if (from.battlestep() != 0) {
    set_battlestep(from.battlestep());
  }
  if (from.developstep() != 0) {
    set_developstep(from.developstep());
  }
  if (from.auxiliarystep() != 0) {
    set_auxiliarystep(from.auxiliarystep());
  }
  if (from.battleextra() != 0) {
    set_battleextra(from.battleextra());
  }
  if (from.developextra() != 0) {
    set_developextra(from.developextra());
  }
  if (from.auxiliaryextra() != 0) {
    set_auxiliaryextra(from.auxiliaryextra());
  }
  if (from.itemid() != 0) {
    set_itemid(from.itemid());
  }
  if (from.itemcount() != 0) {
    set_itemcount(from.itemcount());
  }
  if (from.exchangeitemid() != 0) {
    set_exchangeitemid(from.exchangeitemid());
  }
  if (from.pic() != 0) {
    set_pic(from.pic());
  }
  if (from.show_hero() != 0) {
    set_show_hero(from.show_hero());
  }
}

void hero::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:TableProto.hero)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void hero::CopyFrom(const hero& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TableProto.hero)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool hero::IsInitialized() const {
  return true;
}

void hero::Swap(hero* other) {
  if (other == this) return;
  InternalSwap(other);
}
void hero::InternalSwap(hero* other) {
  using std::swap;
  recomme_skill_.InternalSwap(&other->recomme_skill_);
  name_.Swap(&other->name_);
  initials_.Swap(&other->initials_);
  tab_.Swap(&other->tab_);
  des_.Swap(&other->des_);
  swap(id_, other->id_);
  swap(type_, other->type_);
  swap(level_, other->level_);
  swap(baseskill_, other->baseskill_);
  swap(battle_, other->battle_);
  swap(develop_, other->develop_);
  swap(auxiliary_, other->auxiliary_);
  swap(battlebase_, other->battlebase_);
  swap(developbase_, other->developbase_);
  swap(auxiliarybase_, other->auxiliarybase_);
  swap(battlestep_, other->battlestep_);
  swap(developstep_, other->developstep_);
  swap(auxiliarystep_, other->auxiliarystep_);
  swap(battleextra_, other->battleextra_);
  swap(developextra_, other->developextra_);
  swap(auxiliaryextra_, other->auxiliaryextra_);
  swap(itemid_, other->itemid_);
  swap(itemcount_, other->itemcount_);
  swap(exchangeitemid_, other->exchangeitemid_);
  swap(pic_, other->pic_);
  swap(show_hero_, other->show_hero_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata hero::GetMetadata() const {
  protobuf_hero_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_hero_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// hero

// int64 ID = 1;
void hero::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 hero::id() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.ID)
  return id_;
}
void hero::set_id(::google::protobuf::int64 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.ID)
}

// string Name = 2;
void hero::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& hero::name() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.Name)
  return name_.GetNoArena();
}
void hero::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:TableProto.hero.Name)
}
#if LANG_CXX11
void hero::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:TableProto.hero.Name)
}
#endif
void hero::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:TableProto.hero.Name)
}
void hero::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:TableProto.hero.Name)
}
::std::string* hero::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:TableProto.hero.Name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* hero::release_name() {
  // @@protoc_insertion_point(field_release:TableProto.hero.Name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void hero::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:TableProto.hero.Name)
}

// string Initials = 3;
void hero::clear_initials() {
  initials_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& hero::initials() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.Initials)
  return initials_.GetNoArena();
}
void hero::set_initials(const ::std::string& value) {
  
  initials_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:TableProto.hero.Initials)
}
#if LANG_CXX11
void hero::set_initials(::std::string&& value) {
  
  initials_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:TableProto.hero.Initials)
}
#endif
void hero::set_initials(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  initials_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:TableProto.hero.Initials)
}
void hero::set_initials(const char* value, size_t size) {
  
  initials_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:TableProto.hero.Initials)
}
::std::string* hero::mutable_initials() {
  
  // @@protoc_insertion_point(field_mutable:TableProto.hero.Initials)
  return initials_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* hero::release_initials() {
  // @@protoc_insertion_point(field_release:TableProto.hero.Initials)
  
  return initials_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void hero::set_allocated_initials(::std::string* initials) {
  if (initials != NULL) {
    
  } else {
    
  }
  initials_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), initials);
  // @@protoc_insertion_point(field_set_allocated:TableProto.hero.Initials)
}

// int64 Type = 4;
void hero::clear_type() {
  type_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 hero::type() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.Type)
  return type_;
}
void hero::set_type(::google::protobuf::int64 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.Type)
}

// int64 Level = 5;
void hero::clear_level() {
  level_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 hero::level() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.Level)
  return level_;
}
void hero::set_level(::google::protobuf::int64 value) {
  
  level_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.Level)
}

// int64 BaseSkill = 6;
void hero::clear_baseskill() {
  baseskill_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 hero::baseskill() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.BaseSkill)
  return baseskill_;
}
void hero::set_baseskill(::google::protobuf::int64 value) {
  
  baseskill_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.BaseSkill)
}

// int64 Battle = 7;
void hero::clear_battle() {
  battle_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 hero::battle() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.Battle)
  return battle_;
}
void hero::set_battle(::google::protobuf::int64 value) {
  
  battle_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.Battle)
}

// int64 Develop = 8;
void hero::clear_develop() {
  develop_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 hero::develop() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.Develop)
  return develop_;
}
void hero::set_develop(::google::protobuf::int64 value) {
  
  develop_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.Develop)
}

// int64 Auxiliary = 9;
void hero::clear_auxiliary() {
  auxiliary_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 hero::auxiliary() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.Auxiliary)
  return auxiliary_;
}
void hero::set_auxiliary(::google::protobuf::int64 value) {
  
  auxiliary_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.Auxiliary)
}

// int64 BattleBase = 10;
void hero::clear_battlebase() {
  battlebase_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 hero::battlebase() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.BattleBase)
  return battlebase_;
}
void hero::set_battlebase(::google::protobuf::int64 value) {
  
  battlebase_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.BattleBase)
}

// int64 DevelopBase = 11;
void hero::clear_developbase() {
  developbase_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 hero::developbase() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.DevelopBase)
  return developbase_;
}
void hero::set_developbase(::google::protobuf::int64 value) {
  
  developbase_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.DevelopBase)
}

// int64 AuxiliaryBase = 12;
void hero::clear_auxiliarybase() {
  auxiliarybase_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 hero::auxiliarybase() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.AuxiliaryBase)
  return auxiliarybase_;
}
void hero::set_auxiliarybase(::google::protobuf::int64 value) {
  
  auxiliarybase_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.AuxiliaryBase)
}

// int64 BattleStep = 13;
void hero::clear_battlestep() {
  battlestep_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 hero::battlestep() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.BattleStep)
  return battlestep_;
}
void hero::set_battlestep(::google::protobuf::int64 value) {
  
  battlestep_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.BattleStep)
}

// int64 DevelopStep = 14;
void hero::clear_developstep() {
  developstep_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 hero::developstep() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.DevelopStep)
  return developstep_;
}
void hero::set_developstep(::google::protobuf::int64 value) {
  
  developstep_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.DevelopStep)
}

// int64 AuxiliaryStep = 15;
void hero::clear_auxiliarystep() {
  auxiliarystep_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 hero::auxiliarystep() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.AuxiliaryStep)
  return auxiliarystep_;
}
void hero::set_auxiliarystep(::google::protobuf::int64 value) {
  
  auxiliarystep_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.AuxiliaryStep)
}

// int64 BattleExtra = 16;
void hero::clear_battleextra() {
  battleextra_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 hero::battleextra() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.BattleExtra)
  return battleextra_;
}
void hero::set_battleextra(::google::protobuf::int64 value) {
  
  battleextra_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.BattleExtra)
}

// int64 DevelopExtra = 17;
void hero::clear_developextra() {
  developextra_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 hero::developextra() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.DevelopExtra)
  return developextra_;
}
void hero::set_developextra(::google::protobuf::int64 value) {
  
  developextra_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.DevelopExtra)
}

// int64 AuxiliaryExtra = 18;
void hero::clear_auxiliaryextra() {
  auxiliaryextra_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 hero::auxiliaryextra() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.AuxiliaryExtra)
  return auxiliaryextra_;
}
void hero::set_auxiliaryextra(::google::protobuf::int64 value) {
  
  auxiliaryextra_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.AuxiliaryExtra)
}

// int64 ItemID = 19;
void hero::clear_itemid() {
  itemid_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 hero::itemid() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.ItemID)
  return itemid_;
}
void hero::set_itemid(::google::protobuf::int64 value) {
  
  itemid_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.ItemID)
}

// int64 ItemCount = 20;
void hero::clear_itemcount() {
  itemcount_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 hero::itemcount() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.ItemCount)
  return itemcount_;
}
void hero::set_itemcount(::google::protobuf::int64 value) {
  
  itemcount_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.ItemCount)
}

// int64 ExchangeItemID = 21;
void hero::clear_exchangeitemid() {
  exchangeitemid_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 hero::exchangeitemid() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.ExchangeItemID)
  return exchangeitemid_;
}
void hero::set_exchangeitemid(::google::protobuf::int64 value) {
  
  exchangeitemid_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.ExchangeItemID)
}

// string Tab = 22;
void hero::clear_tab() {
  tab_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& hero::tab() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.Tab)
  return tab_.GetNoArena();
}
void hero::set_tab(const ::std::string& value) {
  
  tab_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:TableProto.hero.Tab)
}
#if LANG_CXX11
void hero::set_tab(::std::string&& value) {
  
  tab_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:TableProto.hero.Tab)
}
#endif
void hero::set_tab(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  tab_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:TableProto.hero.Tab)
}
void hero::set_tab(const char* value, size_t size) {
  
  tab_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:TableProto.hero.Tab)
}
::std::string* hero::mutable_tab() {
  
  // @@protoc_insertion_point(field_mutable:TableProto.hero.Tab)
  return tab_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* hero::release_tab() {
  // @@protoc_insertion_point(field_release:TableProto.hero.Tab)
  
  return tab_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void hero::set_allocated_tab(::std::string* tab) {
  if (tab != NULL) {
    
  } else {
    
  }
  tab_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), tab);
  // @@protoc_insertion_point(field_set_allocated:TableProto.hero.Tab)
}

// string Des = 23;
void hero::clear_des() {
  des_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& hero::des() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.Des)
  return des_.GetNoArena();
}
void hero::set_des(const ::std::string& value) {
  
  des_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:TableProto.hero.Des)
}
#if LANG_CXX11
void hero::set_des(::std::string&& value) {
  
  des_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:TableProto.hero.Des)
}
#endif
void hero::set_des(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  des_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:TableProto.hero.Des)
}
void hero::set_des(const char* value, size_t size) {
  
  des_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:TableProto.hero.Des)
}
::std::string* hero::mutable_des() {
  
  // @@protoc_insertion_point(field_mutable:TableProto.hero.Des)
  return des_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* hero::release_des() {
  // @@protoc_insertion_point(field_release:TableProto.hero.Des)
  
  return des_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void hero::set_allocated_des(::std::string* des) {
  if (des != NULL) {
    
  } else {
    
  }
  des_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), des);
  // @@protoc_insertion_point(field_set_allocated:TableProto.hero.Des)
}

// int64 Pic = 24;
void hero::clear_pic() {
  pic_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 hero::pic() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.Pic)
  return pic_;
}
void hero::set_pic(::google::protobuf::int64 value) {
  
  pic_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.Pic)
}

// int64 Show_hero = 25;
void hero::clear_show_hero() {
  show_hero_ = GOOGLE_LONGLONG(0);
}
::google::protobuf::int64 hero::show_hero() const {
  // @@protoc_insertion_point(field_get:TableProto.hero.Show_hero)
  return show_hero_;
}
void hero::set_show_hero(::google::protobuf::int64 value) {
  
  show_hero_ = value;
  // @@protoc_insertion_point(field_set:TableProto.hero.Show_hero)
}

// repeated int64 recomme_skill = 26;
int hero::recomme_skill_size() const {
  return recomme_skill_.size();
}
void hero::clear_recomme_skill() {
  recomme_skill_.Clear();
}
::google::protobuf::int64 hero::recomme_skill(int index) const {
  // @@protoc_insertion_point(field_get:TableProto.hero.recomme_skill)
  return recomme_skill_.Get(index);
}
void hero::set_recomme_skill(int index, ::google::protobuf::int64 value) {
  recomme_skill_.Set(index, value);
  // @@protoc_insertion_point(field_set:TableProto.hero.recomme_skill)
}
void hero::add_recomme_skill(::google::protobuf::int64 value) {
  recomme_skill_.Add(value);
  // @@protoc_insertion_point(field_add:TableProto.hero.recomme_skill)
}
const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
hero::recomme_skill() const {
  // @@protoc_insertion_point(field_list:TableProto.hero.recomme_skill)
  return recomme_skill_;
}
::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
hero::mutable_recomme_skill() {
  // @@protoc_insertion_point(field_mutable_list:TableProto.hero.recomme_skill)
  return &recomme_skill_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace TableProto

// @@protoc_insertion_point(global_scope)
